CREATE TABLE IF NOT EXISTS `#__dart_clubs` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `city` VARCHAR(150) DEFAULT '',
  `country` VARCHAR(100) DEFAULT '',
  `founded` DATE DEFAULT NULL,
  `website` VARCHAR(255) DEFAULT '',
  `logo` VARCHAR(255) DEFAULT '',
  `published` TINYINT(1) NOT NULL DEFAULT 1,
  `ordering` INT UNSIGNED NOT NULL DEFAULT 0,
  `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
